const tweets = [
  "Yo, I just saw $A$ in $1$",
  "It turns out $A$ is in $1$ now",
  "Just when I thought he's not around, $A$ is in $1$",
  "Am I the only one who just saw $A$ in $1$?",
  "Quit moving around! $A$ is in $1$ now.",
  "THIS JUST IN: $A$ is in $1$",
  "OKAY SO THIS JUST HAPPENED! $A$ is in $1$",
  "Haha so $A$ is in $1$ now, let's see what's next",
  "If you're looking for $A$, he's in $1$",
  "I'll tell you how it is: $A$ is in $1$",
  "I'm just sitting here... and $A$ is in $1$",
  "Maybe I should stalk someone else... but $A$ is in $1$",
  "I just saw $A$ in $1$ and I'm thinking... maybe I should do something better with my time?",
  "When I'm bored, I try to find $A$. He's in $1$.",
  "To all those who are looking for $A$: he's in $1$",
  "You didn't hear it from me, but $A$ is in $1$",
  "Don't tell him I told you, but $A$ is in $1$",
  "Locating... locating... loca---FOUND! $A$ is in $1$",
  "Have you been to $1$? That's where $A$ is",
  "me:\n$A$: is in $1$",
  "I'm going to tell my kids $A$ is in $1$",
  "world: exists\n$A$: goes to $1$",
  "I'm soooo bored... Oh, and $A$ is in $1$",
  "He's just been on the move, guys! $A$ is now in $1$!",
  "Whaaatttttt!!!! $A$ is in $1$!!!!",
  "That's my kind of city... $1$. That's where $A$ is.",
  "I always say: Where do you find $A$? In $1$, that's where.",
  "To all the boys i've loved before... $A$ is in $1$",
  "Just keep stalking, $A$ is in $1$ https://imgflip.com/i/3hr2f6",
  "But $A$ is in $1$!!! https://imgflip.com/i/3hr2ie",
  "That's what I do... $A$ is in $1$ https://imgflip.com/i/3hr2rg",
  "Oh my my my $A$ is in $1$ https://imgflip.com/i/3hr2ul",
  "That's right $A$ is in $1$ https://imgflip.com/i/3hr336",
  "You really think so? BTW it's $1$ https://imgflip.com/i/3hr35u",
  "Oh by the way, $A$ is currently hanging out in $1$",
  "Is $1$ the best stop to hang out in? That's where $A$ is so idk",
  "You might try but $1$ is where $A$ is https://imgflip.com/i/3hr3c6",
  "That's just what I do... $A$ is in $1$ https://imgflip.com/i/3hr3ee",
  "Okay boomer, $A$ is @ $1$ https://imgflip.com/i/3hr3iq",
  "Seriously, $A$ is in $1$ https://imgflip.com/i/3hr3oq",
  "You really think I'm creepy? :( $A$ is in $1$ https://imgflip.com/i/3hr3s3",
  "I swear $A$ is in $1$ https://imgflip.com/i/3hr3v6",
  "You don't want to get on my bad side, $1$ is where $A$ is https://imgflip.com/i/3hr3yp",
  "But I did find $A$ in $1$ https://imgflip.com/i/3hr40t",
  "Safety first, $A$ is in $1$ https://imgflip.com/i/3hr4d6",
  "Okay boomer, $A$ is @ $1$ https://imgflip.com/i/3hr4gl",
  "So he agrees! $A$ is in $1$ https://imgflip.com/i/3hr4jw",
  "Don't @ me but $A$ is in $1$",
  "So for everyone, $A$ is now in $1$ https://imgflip.com/i/3hr4od",
  "I promise 100% approval. Or not. Or $A$ is in $1$. One of them. https://imgflip.com/i/3hr4sw",
  "So $A$ was last seen in $1$ https://imgflip.com/i/3hr4y2",
  "If you want to find $A$, you must go to $1$",
  "Let's see where $A$ is... OH $1$ https://imgflip.com/i/3hr527",
  "Brace brace! $A$ is in $1$ https://imgflip.com/i/3hr57h",
  "Everyone knows it's me! $A$ is in $1$ https://imgflip.com/i/3hr599",
  "Because you made me, $A$ is in $1$ https://imgflip.com/i/3hr5do",
  "Not easy to find but $A$ is in $1$ https://imgflip.com/i/3hr5fr",
  "Bad luck $A$, at $1$ https://imgflip.com/i/3hr5i6",
  "Yeah, because I didn't... $A$ is in $1$ btw https://imgflip.com/i/3hr5l4",
  "That's what $A$ said but he's in $1$ now https://imgflip.com/i/3hr5p0",
  "Everywhere... $A$ is in $1$ right now though https://imgflip.com/i/3huqp2",
  "Nah thanks, I'm good... $A$ is in $1$ https://imgflip.com/i/3huqti",
  "Okay I will, but $A$ is in $1$ https://imgflip.com/i/3huqzg",
  "Well yes but $A$ is in $1$ https://imgflip.com/i/3hur4k",
  "roses are red\nviolets are blue\n$A$ is currently in\n$1$",
  "I WANT YOU but $A$ is in $1$ https://imgflip.com/i/3hurai",
  "That is pretty good... and $A$ is in $1$ https://imgflip.com/i/3hurdh",
  "Okay Mr. President, $A$ is in $1$ https://imgflip.com/i/3hurgl",
  "Do you think $A$ is in $1$? I do! https://imgflip.com/i/3hurl2",
  "But if you think $A$ is in $1$, you're right https://imgflip.com/i/3huro9",
  "Okay internet, $A$ is in $1$ https://imgflip.com/i/3hurq0",
  "At least you guys agree... $A$ is in $1$ https://imgflip.com/i/3hurs0",
  "I remember! $A$ is in $1$ https://imgflip.com/i/3hurv1",
  "Do we really want that? $A$ is in $1$ https://imgflip.com/i/3hurxp",
  "He's really angry lol... $A$ is in $1$ https://imgflip.com/i/3hus1b"
];

export const generateLocationTweet = (location: string) => {
  const randomTweet = tweets[Math.floor(Math.random() * tweets.length)];
  return randomTweet.replace("$A$", "@AnandChowdhary").replace("$1$", location);
};
