# These are document IDs to fetch for the `writing` repo
# For example, "1Nwbt6I1YF6a20t3e3dlz5ID-zVSB2amYHth3YVdtTJQ" -> https://docs.google.com/document/d/1Nwbt6I1YF6a20t3e3dlz5ID-zVSB2amYHth3YVdtTJQ/edit#
googleDocs:
  - 1Nwbt6I1YF6a20t3e3dlz5ID-zVSB2amYHth3YVdtTJQ
